environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  # Log versions for debugging
  - java -version
  - mvn --version
  
build_script:
  - ps: .\Update-Version.ps1
  - cmd: mvn --batch-mode -DskipTests package

artifacts:
  - path: pom.xml
  - path: target\**\*.jar
  - path: target\**\*.hpi